# Generated by Django 4.1.5 on 2023-02-27 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameenegari',
            name='text',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
